<?php

namespace mix\coroutine;

use mix\base\Component;

/**
 * ConnectionPool组件
 * @author 刘健 <coder.liu@qq.com>
 */
class ConnectionPool extends Component
{

    // 最小连接数
    public $min;

    // 最大连接数
    public $max;

    // 生存时间
    public $maxLifetime;

    // 队列
    protected $_queue;

    // 活跃连接数
    protected $_activeCount = 0;

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 设置协程模式
        $this->setCoroutineMode(Component::COROUTINE_MODE_REFERENCE);
        // 创建协程队列
        $this->_queue = new \Swoole\Coroutine\Channel($this->min);
    }

    // 获取队列中的连接数
    public function getQueueCount()
    {
        $count = $this->_queue->stats()['queue_num'];
        return $count < 0 ? 0 : $count;
    }

    // 获取活跃的连接数
    public function getActiveCount()
    {
        return $this->_activeCount;
    }

    // 获取当前总连接数
    public function getCurrentCount()
    {
        return $this->getQueueCount() + $this->getActiveCount();
    }

    // 活跃连接数自增
    public function activeCountIncrement()
    {
        return ++$this->_activeCount;
    }

    // 活跃连接数自减
    public function activeCountDecrement()
    {
        return --$this->_activeCount;
    }

    // 放入连接
    public function push($connection)
    {
        $this->activeCountDecrement();
        if ($this->getQueueCount() < $this->min) {
            return $this->_queue->push([$connection, time()]);
        }
        return false;
    }

    // 弹出连接
    public function pop()
    {
        while (true) {
            list($connection, $activeTime) = $this->_queue->pop();
            if ($activeTime + $this->maxLifetime < time()) {
                return false;
            }
            $this->activeCountIncrement();
            return $connection;
        }
    }

}
