<?php

namespace mix\coroutine;

use mix\client\BaseRedis;
use mix\helpers\CoroutineHelper;

/**
 * Redis组件
 * @author 刘健 <coder.liu@qq.com>
 */
class Redis extends BaseRedis
{

    /**
     * 连接池
     * @var \mix\coroutine\ConnectionPool
     */
    public $connectionPool;

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 开启协程
        CoroutineHelper::enableCoroutine();
    }

    // 析构事件
    public function onDestruct()
    {
        parent::onDestruct();
        // 关闭连接
        $this->disconnect();
    }

    // 创建连接
    protected function createConnection()
    {
        $this->connectionPool->activeCountIncrement();
        $redis = parent::createConnection();
        return $redis;
    }

    // 获取连接
    protected function getConnection()
    {
        while ($this->connectionPool->getQueueCount() > 0) {
            $connection = $this->connectionPool->pop();
            if ($connection) {
                return $connection;
            }
        }
        while ($this->connectionPool->getCurrentCount() >= $this->connectionPool->max) {
            $connection = $this->connectionPool->pop();
            if ($connection) {
                return $connection;
            }
        }
        return $this->createConnection();
    }

    // 连接
    protected function connect()
    {
        $this->_redis = $this->getConnection();
    }

    // 关闭连接
    public function disconnect()
    {
        if (isset($this->_redis)) {
            $this->connectionPool->push($this->_redis);
            $this->connectionPool->activeCountDecrement();
        }
        parent::disconnect();
    }

    // 执行命令
    public function __call($name, $arguments)
    {
        try {
            // 执行命令
            return parent::__call($name, $arguments);
        } catch (\Throwable $e) {
            // 销毁失效连接
            parent::disconnect();
            // 抛出异常
            throw $e;
        }
    }

}
