<?php

namespace Mix\Pool;

use Mix\Core\Component\Component;
use Mix\Core\Component\ComponentInterface;

/**
 * Class ConnectionPool
 * @author LIUJIAN <coder.keda@gmail.com>
 * @package Mix\Pool
 */
abstract class ConnectionPool extends Component
{

    /**
     * 协程模式
     * @var int
     */
    public static $coroutineMode = ComponentInterface::COROUTINE_MODE_REFERENCE;

    /**
     * 最多可空闲连接数
     * @var int
     */
    public $maxIdle = 5;

    /**
     * 最大连接数
     * @var int
     */
    public $maxActive = 5;

    /**
     * 拨号依赖引用
     * @var \Mix\Pool\DialInterface
     */
    public $dial;

    /**
     * 连接队列
     * @var \Swoole\Coroutine\Channel
     */
    protected $_queue;

    /**
     * 连接的hashid
     * @var array
     */
    protected $_hash;

    /**
     * 活跃连接集合
     * @var int
     */
    protected $_actives = 0;

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 创建协程队列
        $this->_queue = new \Swoole\Coroutine\Channel($this->maxIdle);
    }

    /**
     * 创建连接
     * @return mixed
     */
    protected function createConnection()
    {
        $connection = $this->dial->handle();
        $connection->connectionPool = $this;
        return $connection;
    }

    /**
     * 获取连接
     * @return mixed
     */
    public function getConnection()
    {
        if ($this->getIdleNumber() > 0 || $this->getTotalNumber() >= $this->maxActive) {
            // 队列有连接，从队列取
            // 达到最大连接数，从队列取
            $connection = $this->pop();
        } else {
            // 创建连接
            $connection = $this->createConnection();
        }
        // 标记
        $id = spl_object_hash($connection);
        $this->_hash[$id] = 1;
        // 加活动数
        $this->_actives++;
        return $connection;
    }

    /**
     * 释放连接
     * @param $connection
     * @return bool
     */
    public function release($connection)
    {
        // 判断是否已丢弃
        $id = spl_object_hash($connection);
        if (!isset($this->_hash[$id])) {
            return false;
        }
        // 判断是否已释放
        if ($this->_hash[$id] === 0) {
            return false;
        }
        // 标记
        $id = spl_object_hash($connection);
        $this->_hash[$id] = 0;
        // 入列并减活动数
        $this->push($connection);
        $this->_actives--;
        return true;
    }

    /**
     * 丢弃连接
     * @param $connection
     * @return bool
     */
    public function discard($connection)
    {
        // 判断是否已丢弃
        $id = spl_object_hash($connection);
        if (!isset($this->_hash[$id])) {
            return false;
        }
        // 移除标记
        unset($this->_hash[$id]);
        // 减活动数
        $this->_actives--;
        return true;
    }

    /**
     * 获取连接池的统计信息
     * @return array
     */
    public function getStats()
    {
        return [
            'total'  => $this->getTotalNumber(),
            'idle'   => $this->getIdleNumber(),
            'active' => $this->getActiveNumber(),
        ];
    }

    /**
     * 放入连接
     * @param $connection
     * @return bool
     */
    protected function push($connection)
    {
        if ($this->getIdleNumber() < $this->maxIdle) {
            return $this->_queue->push($connection);
        }
        return false;
    }

    /**
     * 弹出连接
     * @return mixed
     */
    protected function pop()
    {
        return $this->_queue->pop();
    }

    /**
     * 获取队列中的连接数
     * @return int
     */
    protected function getIdleNumber()
    {
        $count = $this->_queue->stats()['queue_num'];
        return $count < 0 ? 0 : $count;
    }

    /**
     * 获取活跃的连接数
     * @return int
     */
    protected function getActiveNumber()
    {
        return $this->_actives;
    }

    /**
     * 获取当前总连接数
     * @return int
     */
    protected function getTotalNumber()
    {
        return $this->getIdleNumber() + $this->getActiveNumber();
    }

}
