<?php

namespace Mix\Database\Coroutine;

use Mix\Pool\ConnectionPool;
use Mix\Pool\ConnectionPoolInterface;

/**
 * Class PDOPool
 * @author LIUJIAN <coder.keda@gmail.com>
 */
class PDOPool extends ConnectionPool implements ConnectionPoolInterface
{

    // 数据源格式
    public $dsn = '';

    // 数据库用户名
    public $username = 'root';

    // 数据库密码
    public $password = '';

    // 驱动连接选项
    public $driverOptions = [];

    // 创建连接
    public function createConnection()
    {
        $connection = new PDOConnection([
            'connectionPool' => $this,
            'dsn'            => $this->dsn,
            'username'       => $this->username,
            'password'       => $this->password,
            'driverOptions'  => $this->driverOptions,
        ]);
        return $connection;
    }

    /**
     * 获取连接
     * @return PDOConnection
     */
    public function getConnection()
    {
        return parent::getConnection(); // TODO: Change the autogenerated stub
    }

}
