<?php

namespace Mix\Core;

use Mix\Container\Container;

/**
 * App类
 * @author 刘健 <coder.liu@qq.com>
 *
 * @property \Mix\Log\Log $log
 * @property \Mix\Console\Input $input
 * @property \Mix\Console\Output $output
 * @property \Mix\Http\Route $route
 * @property \Mix\Http\Request|\Mix\Http\Compatible\Request $request
 * @property \Mix\Http\Response|\Mix\Http\Compatible\Response $response
 * @property \Mix\Http\Error|\Mix\Console\Error $error
 * @property \Mix\Http\Token $token
 * @property \Mix\Http\Session $session
 * @property \Mix\Http\Cookie $cookie
 * @property \Mix\Database\PDOConnection $pdo
 * @property \Mix\Redis\RedisConnection $redis
 * @property \Mix\WebSocket\TokenReader $tokenReader
 * @property \Mix\WebSocket\SessionReader $sessionReader
 * @property \Mix\WebSocket\MessageHandler $messageHandler
 * @property \Mix\Pool\ConnectionPool $connectionPool
 */
class Application extends BaseObject
{

    // 初始化回调
    public $initialize = [];

    // 基础路径
    public $basePath = '';

    // 组件配置
    public $components = [];

    // 类库配置
    public $libraries = [];

    /**
     * 容器
     * @var \Mix\Container\Container
     */
    public $container;

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 快捷引用
        \Mix::$app = $this;
        // 实例化容器
        $this->container = new Container([
            'config' => $this->components,
        ]);
        // 错误注册
        \Mix\Core\Error::register();
        // 转换类库配置
        $libraries       = $this->libraries;
        $this->libraries = [];
        foreach ($libraries as $item) {
            if (!isset($item['class'])) {
                throw new \Mix\Exceptions\ConfigException("类库配置错误");
            }
            if (!isset($item['name'])) {
                throw new \Mix\Exceptions\ConfigException("没有配置名称：{$item['class']}");
            }
            $name                   = "{$item['class']}:{$item['name']}";
            $this->libraries[$name] = $item;
        }
        // 执行初始化回调
        foreach ($this->initialize as $callback) {
            call_user_func($callback);
        }
    }

    // 获取配置
    public function config($name)
    {
        $message   = "Config does not exist: {$name}.";
        $fragments = explode('.', $name);
        // 判断一级配置是否存在
        $first = array_shift($fragments);
        if (!isset($this->$first)) {
            throw new \Mix\Exceptions\ConfigException($message);
        }
        // 判断其他配置是否存在
        $current = $this->$first;
        foreach ($fragments as $key) {
            if (!isset($current[$key])) {
                throw new \Mix\Exceptions\ConfigException($message);
            }
            $current = $current[$key];
        }
        return $current;
    }

    // 获取配置目录路径
    public function getConfigPath()
    {
        return $this->basePath . DIRECTORY_SEPARATOR . 'config';
    }

    // 获取运行目录路径
    public function getRuntimePath()
    {
        return $this->basePath . DIRECTORY_SEPARATOR . 'runtime';
    }

}
