<?php

namespace Mix\Core;

/**
 * 通道类
 * @author LIUJIAN <coder.keda@gmail.com>
 */
class Channel extends \Swoole\Coroutine\Channel
{

    /**
     * 抛出数据
     * @return mixed
     * @throws \Throwable
     */
    public function pop($timeout = 0)
    {
        $data = parent::pop($timeout); // TODO: Change the autogenerated stub
        if ($data instanceof \Throwable) {
            throw $data;
        }
        return $data;
    }

}
