<?php

namespace Mix\Redis\Coroutine;

use Mix\Core\Coroutine;

/**
 * RedisCoroutine组件
 * @author 刘健 <coder.liu@qq.com>
 */
class RedisConnection extends \Mix\Redis\Persistent\BaseRedisConnection
{

    /**
     * 连接池
     * @var \Mix\Pool\ConnectionPool
     */
    public $connectionPool;

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 池判断
        if (!isset($this->connectionPool)) {
            throw new \RedisException('\'' . get_class($this) . '\' can only be returned through the \'Mix\Redis\Coroutine\RedisPool\'.');
        }
        // 开启协程
        Coroutine::enable();
    }

    // 析构事件
    public function onDestruct()
    {
        parent::onDestruct(); // TODO: Change the autogenerated stub
        // 释放连接
        $this->connectionPool->release($this);
    }

}
